import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { calcDur, calcEarnings, fmtCAD, dayKey } from './utils.js';
import { CRA_RATE } from './constants.js';

export default function generateInvoice({ sessions, jobs, employees, mileage, dateRange, companyName, clientName, invoiceNum }) {
  const [rs, re] = dateRange;
  const f = sessions.filter(s => {
    const t = new Date(s.start_time);
    return t >= rs && t <= re && s.end_time;
  });
  const fm = mileage.filter(m => {
    const t = new Date(m.date);
    return t >= rs && t <= re;
  });

  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 14, 22);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  if (companyName) doc.text(companyName, 14, 30);
  doc.text(`Invoice #: ${invoiceNum || 'INV-001'}`, pw - 14, 22, { align: 'right' });
  doc.text(`Date: ${new Date().toLocaleDateString('en-CA')}`, pw - 14, 28, { align: 'right' });
  doc.text(`Period: ${rs.toLocaleDateString('en-CA')} to ${re.toLocaleDateString('en-CA')}`, pw - 14, 34, { align: 'right' });

  if (clientName) {
    doc.text('Bill To:', 14, 42);
    doc.setFont('helvetica', 'bold');
    doc.text(clientName, 14, 48);
    doc.setFont('helvetica', 'normal');
  }

  let y = clientName ? 58 : 44;

  // Labour table
  const labourRows = f.map(s => {
    const j = jobs.find(x => x.id === s.job_id);
    const emp = employees.find(x => x.id === s.employee_id);
    const hrs = (calcDur(s) / 3600000).toFixed(2);
    const earn = calcEarnings(s, jobs);
    return [
      new Date(s.start_time).toLocaleDateString('en-CA'),
      j?.name || '',
      emp?.name || 'Owner',
      hrs,
      fmtCAD(j?.rate || 0) + '/hr',
      fmtCAD(earn)
    ];
  });

  const totalEarnings = f.reduce((s, x) => s + calcEarnings(x, jobs), 0);
  const totalHours = (f.reduce((s, x) => s + calcDur(x), 0) / 3600000).toFixed(2);

  if (labourRows.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Labour', 14, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      head: [['Date', 'Job', 'Employee', 'Hours', 'Rate', 'Amount']],
      body: labourRows,
      foot: [['', '', 'Total', totalHours, '', fmtCAD(totalEarnings)]],
      theme: 'grid',
      headStyles: { fillColor: [232, 101, 26], textColor: 255, fontStyle: 'bold', fontSize: 9 },
      footStyles: { fillColor: [245, 245, 245], textColor: [0, 0, 0], fontStyle: 'bold', fontSize: 9 },
      styles: { fontSize: 8, cellPadding: 3 },
      columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } },
    });

    y = doc.lastAutoTable.finalY + 12;
  }

  // Mileage table
  const totalKm = fm.reduce((s, x) => s + Number(x.km), 0);
  if (fm.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Mileage', 14, y);
    y += 4;

    const mileageRows = fm.map(m => {
      const j = jobs.find(x => x.id === m.job_id);
      return [
        new Date(m.date).toLocaleDateString('en-CA'),
        j?.name || '',
        m.origin + ' \u2192 ' + m.destination,
        Number(m.km).toFixed(1) + ' km',
        fmtCAD(Number(m.km) * CRA_RATE)
      ];
    });

    autoTable(doc, {
      startY: y,
      head: [['Date', 'Job', 'Route', 'Distance', 'Deduction']],
      body: mileageRows,
      foot: [['', '', 'Total', totalKm.toFixed(1) + ' km', fmtCAD(totalKm * CRA_RATE)]],
      theme: 'grid',
      headStyles: { fillColor: [232, 101, 26], textColor: 255, fontStyle: 'bold', fontSize: 9 },
      footStyles: { fillColor: [245, 245, 245], textColor: [0, 0, 0], fontStyle: 'bold', fontSize: 9 },
      styles: { fontSize: 8, cellPadding: 3 },
      columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' } },
    });

    y = doc.lastAutoTable.finalY + 12;
  }

  // Grand total
  const grandTotal = totalEarnings + totalKm * CRA_RATE;
  doc.setDrawColor(232, 101, 26);
  doc.setLineWidth(0.5);
  doc.line(pw - 80, y, pw - 14, y);
  y += 8;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Total Due:', pw - 80, y);
  doc.text(fmtCAD(grandTotal), pw - 14, y, { align: 'right' });

  // Footer
  const ph = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text('Generated by SiteLedger', 14, ph - 10);

  doc.save(`invoice-${invoiceNum || 'draft'}-${rs.toLocaleDateString('en-CA')}.pdf`);
}
